name: Deploy Staging

on:
  push:
    branches:
      - staging/*

env:
  TF_PLAN_FILE: tfplan-staging

jobs:
  terraform-plan-staging:
    name: Terraform Plan Staging
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: deployment
    steps:
      # Docs: https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Docs: https://github.com/hashicorp/setup-terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      # Docs: https://github.com/google-github-actions/auth
      - name: GCP Auth
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Docs: https://github.com/google-github-actions/setup-gcloud
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Terraform Init
        run: |
          terraform init 
        
      - name: Terraform Format
        run: | 
          terraform fmt -recursive

      - name: Terraform Plan
        run: |
          terraform workspace select -or-create=true ${{ github.ref == 'refs/heads/main' && 'prod' || 'staging' }}
          terraform plan -var-file=terraform.tfvars -out=$TF_PLAN_FILE
      
      # Docs: https://github.com/actions/upload-artifact
      - name: Upload tfplan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: $TF_PLAN_FILE
          path: deployment/$TF_PLAN_FILE
          retention-days: 1


  terraform-apply-staging:
    name: Terraform Apply staging
    runs-on: ubuntu-latest
    outputs:
      instance_ip: ${{ steps.get_instance_ip.outputs.juice_ip }}
    needs: terraform-plan-staging

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.5  # Ensure the same version as in terraform-plan

    - name: GCP Auth
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Terraform Init
      run: |
        cd deployment
        terraform init 
        
    - name: Download tfplan artifact
      uses: actions/download-artifact@v4
      with:
        name: $TF_PLAN_FILE
        path: deployment

    - name: Terraform Apply Dev
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      run: |
        cd deployment
        terraform workspace select -or-create=true ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
        terraform apply -auto-approve $TF_PLAN_FILE
        echo "{planfile}={$TF_PLAN_FILE}" >> $GITHUB_OUTPUT

    - name: Get Instance IP
      id: get_instance_ip
      run: |
        cd deployment
        echo "juice_ip=$(terraform output -raw juice_shop_instance_ip)" >> $GITHUB_OUTPUT

  zap-scan:
    name: "ZAP Scan Baseline"
    runs-on: ubuntu-latest
    needs: terraform-apply-staging
    continue-on-error: true
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        env: 
          INSTANCE_IP: ${{ needs.terraform-apply-staging.outputs.instance_ip }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          target: "http://${{ env.INSTANCE_IP }}:3000"
          cmd_options: |
            chmod a+rwx '/zap/wrk/zap.yaml'  
          allow_issue_writing: false  

      - name: Upload Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: zap_report.html
          path: .
          retention-days: 1
        
  # terraform-destroy-staging:
  #   name: "Terraform Destroy Development"
  #   runs-on: ubuntu-latest
  #   needs: zap-scan
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v3
  #       with:
  #         terraform_version: 1.8.5  # Ensure the same version as in terraform-plan

  #     - name: GCP Auth
  #       id: 'auth'
  #       uses: 'google-github-actions/auth@v2'
  #       with:
  #         credentials_json: '${{ secrets.GCP_SA_KEY }}'

  #     - name: 'Set up Cloud SDK'
  #       uses: 'google-github-actions/setup-gcloud@v2'

  #     - name: 'Use gcloud CLI'
  #       run: 'gcloud info'

  #     - name: Terraform Init
  #       run: |
  #         cd deployment
  #         terraform init

  #     - name: Terraform Destroy Development
  #       run: |
  #         cd deployment
  #         terraform workspace select -or-create=true ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
  #         terraform destroy -auto-approve -var-file="terraform.tfvars"